version: "3.7"

services:
  nginx:
    #Build an image from Dockerfile in the same directory If not set, pull from docker registry/dockerhub
    build: 
      context: ./
      dockerfile: Dockerfile-https
    container_name: testing-nginx-docker
    restart: always
    working_dir: /etc/nginx
    volumes: 
      - /var/log/nginx:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 80:80
      - 443:443
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks: 
      - nginx-lab
 
networks: 
  nginx-lab:
    name: nginx-lab
