version: "3.7"

services:
  nginx:
     #Ngebuild image dari file Dockerfile pada directory yang sama, jika belum pull dari docker registry/dockerhub
    build: 
      context: ./
      dockerfile: Dockerfile-https
    #image: 192.168.41.29:5000/nginx-test:latest
    #image: 192.168.41.29:5000/nginx:https
    #image: nginx:dearnam3
    container_name: testing-nginx-docker
    restart: always
    working_dir: /etc/nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d/
      - ./log-nginx:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      #- ./testing-nginx:/var/www/html
      #- ./ssl:/etc/nginx/ssl

    ports: 
      - 80:80
      - 443:443
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks: 
      - nginx-lab
 
networks: 
  nginx-lab:
    name: nginx-lab
