kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-ryan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ryan
  template:
    metadata:
      labels:
        app: nginx-ryan
    spec:
      containers:
        - name: nginx-ryan
          image: 192.168.41.29:5000/nginx-testing:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tz
              mountPath: /etc/localtime
              subPath: Jakarta
      volumes:
        - name: tz
          configMap:
            name: tz
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: svc-nginx-ryan
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-ryan

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-nginx-ryan
  namespace: mahaga
spec:
  ingressClassName: private-nginx
  tls:
  - hosts:
    - nginx-ryan.mahaga-pratama.co.id
    secretName: mhg-tls
  rules:
  - host: nginx-ryan.mahaga-pratama.co.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-nginx-ryan
            port: 
              number: 80
